### ISSUE TITLE
manuscript interperation needs fixing.

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/collaboration-demo#3]
@GraceSigalla can you help with fixing the interpreations in the manual? 

the file is here: https://github.com/Drexel-UHC/collaboration-demo/blob/main/outputs/manuscript.md

**Comment by GraceSigalla** [comment]
Hi Ran! I have fixed the issue.

**Comment by ran-codes** [comment]
😄 thanks grace great job!!
